### ISSUE TITLE
Allow "B" button to be pressed instead of A that doesn't drop pixels

### ISSUE THREAD

**Issue by jgonyea** [jgonyea/11208-CenterStage#26]
Right now, pressing the "A" button will pick up pixels from the shovel, but will drop any currently held pixels.  Maybe we can use the "B" button in some way to allow just one pincer to close? Maybe require a chording ("B" + individual bumper?) before plunging downward?

**Comment by jtiffse256** [comment]
I am working on this now

**Comment by jtiffse256** [comment]
Merged into `front_pincers`.
