### ISSUE TITLE
Refine prop detection

### ISSUE THREAD

**Issue by jgonyea** [jgonyea/11208-CenterStage#27]
Prop detection sometimes misses.  Need to find a better/ faster way of detection.

**Comment by jgonyea** [comment]
Possible options:

- Actual vision implementation
- Corroborate the right distance sensor value with left distance value.  Same heading numbers will not match, but we can do math between them to decide which placement was detected (L/C/R).

**Comment by jgonyea** [comment]
New cylindrical prop has increased detection rates.

**Comment by jtiffse256** [comment]
> New cylindrical prop has increased detection rates.

I think this works reliably enough.
