### ISSUE TITLE
Investigate possiblity of passing final heading/ position from autonomous to teleop

### ISSUE THREAD

**Issue by jgonyea** [jgonyea/11208-CenterStage#28]
Having the current position would let us give the drivers some more options for controlling the robot.

**Comment by jtiffse256** [comment]
Relevant link: [Transferring Pose Between Opmodes](https://learnroadrunner.com/advanced.html#transferring-pose-between-opmodes)

**Comment by jgonyea** [comment]
Also, updating the current pose based on AprilTags observed from the camera

**Comment by jtiffse256** [comment]
The method used in [Transferring Pose Between Opmodes](https://learnroadrunner.com/advanced.html#transferring-pose-between-opmodes) seems to work, but how does it work though? It does not seem very reliable if the OpMode crashes or the robot reboots.

**Comment by jtiffse256** [comment]
Every test and drive practice, pose passing works perfectly.
