### ISSUE TITLE
Add distance sensing during Auto

### ISSUE THREAD

**Issue by jtiffse256** [jgonyea/11208-CenterStage#35]
This was a note card from the **Do it! - Programming** idea sheet.

**Comment by jgonyea** [comment]
We haven't returned to the distance sensors in a while to find the optimal distance from the board to place pixels.  We should find this value with a real scoreboard

**Comment by jtiffse256** [comment]
The camera could help as well.

**Comment by jtiffse256** [comment]
Done! It works very reliably.
