### ISSUE TITLE
Fix 180-degree turn feature

### ISSUE THREAD

**Issue by jtiffse256** [jgonyea/11208-CenterStage#36]
This was a note card from the **Do it! - Programming** idea sheet.

**Comment by jgonyea** [comment]
Observed behavior is that pressing the driver's Y button does not turn 180.  More debugging would be helpful here to find the root cause.

**Comment by jtiffse256** [comment]
I tried pressing Y and it turned 180 every time, so could this have been a temporary issue with one version of the Y button code that was deployed before a match?

**Comment by jgonyea** [comment]
I don't recall changing anything after we pushed the code fixing the issue.
Could you try turning it to different headings and then pressing Y?

**Comment by jtiffse256** [comment]
That is what I tried, as well as pressing Y while the robot was already moving. It does exactly what it should in every case.

**Comment by jtiffse256** [comment]
The issue seemed to be pressing Y while a 180-turn was already in progress. This is completely fixed with the new logic and target heading code.
