### ISSUE TITLE
Clean up branches?

### ISSUE THREAD

**Issue by jtiffse256** [jgonyea/11208-CenterStage#40]
Should we eventually merge `auto-effector-refactor` into `main` and delete the other unnecessary branches?

**Comment by jgonyea** [comment]
Yes, this should be a priority before too much other code gets worked on.

**Comment by jtiffse256** [comment]
Do we need the `auto` branch? I think the latest code is on `auto-effector-refactor` now.

**Comment by jgonyea** [comment]
Correct, we should take everything in the refractor one and merge that to
main

**Comment by jtiffse256** [comment]
Done
